#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"


AEROSPACE_FOCUSED_MONITOR_NO=$(aerospace list-workspaces --focused)
AEROSPACE_LIST_OF_WINDOWS_IN_FOCUSED_MONITOR=$(aerospace list-windows --workspace $AEROSPACE_FOCUSED_MONITOR_NO | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

sketchybar --bar height=42 \
                 display=main \
                 blur_radius=0 \
                 position=top \
                 sticky=false \
                 corner_radius=10 \
                 margin=10 \
                 y_offset=4 \
                 color=$CAT_BASE

sketchybar --default icon.font="SF Pro:Semibold:13.0" \
                     icon.color=$CAT_TEXT \
                     label.font="SF Pro:Medium:13.0" \
                     label.color=$CAT_TEXT \
                     background.corner_radius=10 \
                     background.height=26 \
                     padding_left=6 \
                     padding_right=6 \

# -- Left Side Items --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# -- Center Items --
source $ITEM_DIR/media.sh

# -- Right Side Items --
source $ITEM_DIR/calendar.sh
# source $ITEM_DIR/volume.sh
# source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh

sketchybar --hotload on

sketchybar --update
