#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

sketchybar --bar height=26 \
                 display=main \
                 blur_radius=0 \
                 position=top \
                 sticky=false \
                 corner_radius=10            \
                 padding_left=20 \
                 padding_right=20 \
                 margin=10 \
                 y_offset=4 \
                 color=$BAR_COLOR

sketchybar --default icon.font="SF Pro:Semibold:13.0" \
                     icon.color=$ITEM_TEXT_COLOR \
                     label.font="SF Pro:Semibold:13.0" \
                     label.color=$ITEM_TEXT_COLOR \
                     background.corner_radius=10            \
                     padding_left=5 \
                     padding_right=5 \
                     label.padding_left=4 \
                     label.padding_right=2 \
                     icon.padding_left=2 \
                     icon.padding_right=4

# -- Left Side Items --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# -- Center Items --
source $ITEM_DIR/media.sh

# -- Right Side Items --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh

sketchybar --update
