-- Enhanced intelephense.lua (focused on navigation/completion)
return {
  environment = {
    phpVersion = "8.3.0",
    includePaths = { "./vendor" },
  },
  stubs = {
    "Core",
    "SPL",
    "Reflection",
    "standard",
    "superglobals",
    "apache",
    "bcmath",
    "bz2",
    "calendar",
    "ctype",
    "curl",
    "date",
    "dba",
    "dom",
    "enchant",
    "exif",
    "FFI",
    "fileinfo",
    "filter",
    "ftp",
    "gd",
    "gettext",
    "gmp",
    "hash",
    "iconv",
    "imap",
    "intl",
    "json",
    "ldap",
    "libxml",
    "mbstring",
    "meta",
    "mysqli",
    "oci8",
    "odbc",
    "openssl",
    "pcntl",
    "pcre",
    "PDO",
    "pdo_mysql",
    "pdo_pgsql",
    "pdo_sqlite",
    "pgsql",
    "Phar",
    "posix",
    "pspell",
    "readline",
    "session",
    "shmop",
    "SimpleXML",
    "snmp",
    "soap",
    "sockets",
    "sodium",
    "sqlite3",
    "sysvmsg",
    "sysvsem",
    "sysvshm",
    "tidy",
    "tokenizer",
    "xml",
    "xmlreader",
    "xmlrpc",
    "xmlwriter",
    "xsl",
    "Zend OPcache",
    "zip",
    "zlib",
    "laravel",
    "lumen",
  },
  files = {
    maxSize = 3000000,
    associations = { "*.php", "*.phtml" },
    exclude = {
      "**/node_modules/**",
      "**/bower_components/**",
      "**/.git/**",
      "**/vendor/**/Tests/**",
      "**/vendor/**/tests/**",
      "**/storage/**",
      "**/cache/**",
      "**/build/**",
      "**/phpstan/**",
      "**/*resultCache*",
      "**/*.cache",
      "**/bootstrap/cache/**",
    },
  },
  completion = {
    insertUseDeclaration = true,
    fullyQualifyGlobalConstantsAndFunctions = false,
    triggerParameterHints = true,
    maxItems = 50,
  },
  diagnostics = {
    enable = true,
    run = "onSave",
    typeErrors = false,
    undefinedTypes = true,
    undefinedFunctions = true,
    undefinedConstants = true,
    undefinedClassConstants = true,
    undefinedMethods = true,
    undefinedProperties = true,
    unusedSymbols = true, -- Disabled for performance
    duplicateSymbols = true,
    argumentCount = true,
    typeCoercion = false, -- Disabled for performance
    missingReturnType = false,
    unnecessaryFQCN = false, -- Disabled for performance
  },
  format = {
    enable = false,
  },
  telemetry = {
    enabled = false,
  },
  on_attach = function(client, bufnr)
    -- Intelephense handles: navigation, completion, hover, diagnostics
    client.server_capabilities.documentFormattingProvider = false
    client.server_capabilities.documentRangeFormattingProvider = false
    -- Disable rename for Intelephense (let phpactor handle it)
    client.server_capabilities.renameProvider = false
  end,
}
