# Generated by 'nixos-generate-config'. Replace with output from your server.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usbhid" "sd_mod" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/14ce8c3a-c937-4cb0-b37e-940a9fb63f84";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/8C1A-5BF1";
      fsType = "vfat";
    };

  fileSystems."/mnt/docker" =
    { device = "/dev/disk/by-uuid/773730c1-9b8c-49dc-8116-fcd2b6d4d253";
      fsType = "ext4";
    };

  fileSystems."/mnt/backup" =
    { device = "/dev/disk/by-uuid/e59017d0-5be8-41a9-9602-15969ef2aeeb";
      fsType = "ext4";
    };

  fileSystems."/mnt/storage" =
    { device = "/dev/disk/by-uuid/F2C44122C440EA85";
      fsType = "ntfs-3g";
      options = [ "rw" "uid=1000" "gid=1000" ];
    };

  fileSystems."/mnt/shows" =
    { device = "/dev/disk/by-uuid/D4BA3D97BA3D76D8";
      fsType = "ntfs-3g";
      options = [ "rw" "uid=1000" "gid=1000" ];
    };

  fileSystems."/mnt/media" =
    { device = "/dev/disk/by-uuid/2AAC97B9AC977E4F";
      fsType = "ntfs-3g";
      options = [ "rw" "uid=1000" "gid=1000" ];
    };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
