return {
  settings = {
    intelephense = {
      -- Explicitly set PHP version
      environment = {
        phpVersion = "8.4.0",
        includePaths = { "./vendor" },
      },
      -- Comprehensive stubs list for PHP 8.4
      stubs = {
        "Core",
        "SPL",
        "Reflection",
        "standard",
        "superglobals",
        "apache",
        "bcmath",
        "bz2",
        "calendar",
        "ctype",
        "curl",
        "date",
        "dba",
        "dom",
        "enchant",
        "exif",
        "FFI",
        "fileinfo",
        "filter",
        "ftp",
        "gd",
        "gettext",
        "gmp",
        "hash",
        "iconv",
        "imap",
        "intl",
        "json",
        "ldap",
        "libxml",
        "mbstring",
        "meta",
        "mysqli",
        "oci8",
        "odbc",
        "openssl",
        "pcntl",
        "pcre",
        "PDO",
        "pdo_mysql",
        "pdo_pgsql",
        "pdo_sqlite",
        "pgsql",
        "Phar",
        "posix",
        "pspell",
        "readline",
        "session",
        "shmop",
        "SimpleXML",
        "snmp",
        "soap",
        "sockets",
        "sodium",
        "sqlite3",
        "sysvmsg",
        "sysvsem",
        "sysvshm",
        "tidy",
        "tokenizer",
        "xml",
        "xmlreader",
        "xmlrpc",
        "xmlwriter",
        "xsl",
        "Zend OPcache",
        "zip",
        "zlib",
        "laravel",
        "lumen",
      },
      files = {
        maxSize = 5000000,
        associations = {
          "*.php",
          "*.phtml",
        },
        exclude = {
          "**/node_modules/**",
          "**/bower_components/**",
          "**/.git/**",
          "**/vendor/**/Tests/**",
          "**/vendor/**/tests/**",
        },
      },
      completion = {
        insertUseDeclaration = true,
        fullyQualifyGlobalConstantsAndFunctions = false,
        triggerParameterHints = true,
        maxItems = 100,
      },
      diagnostics = {
        enable = true,
        run = "onType",
        typeErrors = false,
        undefinedTypes = true,
        undefinedFunctions = true,
        undefinedConstants = true,
        undefinedClassConstants = true,
        undefinedMethods = true,
        undefinedProperties = true,
        unusedSymbols = true,
        duplicateSymbols = true,
        argumentCount = true,
        typeCoercion = true,
        missingReturnType = false,
        unnecessaryFQCN = true,
      },
      format = {
        enable = false,
      },
      rename = {
        exclude = {
          "**/vendor/**",
          "**/node_modules/**",
        },
      },
    },
  },
  on_attach = function(client, bufnr)
    client.server_capabilities.documentFormattingProvider = false
    client.server_capabilities.documentRangeFormattingProvider = false
  end,
}
