return {
  settings = {
    intelephense = {
      stubs = {
        "apache",
        "bcmath",
        "bz2",
        "calendar",
        "Core",
        "curl",
        "date",
        "dom",
        "fileinfo",
        "filter",
        "ftp",
        "gd",
        "gettext",
        "hash",
        "iconv",
        "imap",
        "intl",
        "json",
        "ldap",
        "libxml",
        "mbstring",
        "mcrypt",
        "mysql",
        "mysqli",
        "password",
        "pcntl",
        "pcre",
        "PDO",
        "pdo_mysql",
        "pdo_pgsql",
        "pdo_sqlite",
        "pgsql",
        "Phar",
        "readline",
        "redis",
        "Reflection",
        "session",
        "SimpleXML",
        "soap",
        "sockets",
        "sodium",
        "sqlite3",
        "standard",
        "tokenizer",
        "xml",
        "xmlreader",
        "xmlwriter",
        "Zend OPcache",
        "zip",
        "zlib",
        "laravel",
        "lumen",
      },
      environment = {
        includePaths = { "./vendor" }, -- Adjust path for Laravel's vendor directory
      },
    },
  },
  on_attach = function(client, bufnr)
    client.server_capabilities.documentFormattingProvider = false
    client.server_capabilities.documentRangeFormattingProvider = false
  end,
}
